import json,sys,subprocess,os
from pathlib import Path
from datetime import date
sys.path.insert(0,'/Users/dannywang/Work/SEO-engine')
from scripts.lib import strategy,growth
from scripts.lib.config import Config
r=(Path(__file__).parent/'cold-start-nested').resolve(); cfg=Config(r); today=date.today().isoformat(); report={}
# I authored these from the fixture product/support sources and live source page, not test factories.
claim={'text':'DispatchPad provides CSV job export for HVAC service teams.','kind':'fact','evidence_ids':['catalog']}
u={'author':'Independent Codex Reviewer','business':'DispatchPad is scheduling software for HVAC companies with 2–20 technicians.','conversion_goal':'Request a guided demo; implementation of the demo path still needs locating.','audiences':['HVAC dispatcher and office teams'],'source_files':['app/catalog.json','app/pages.py','app/build.py'],'seed_queries':['HVAC job CSV export','HVAC daily dispatcher schedule'],'commands':{'test':[sys.executable,'-m','py_compile','app/pages.py','app/build.py'],'build':[sys.executable,'app/build.py']},'unknowns':['Precise CSV column schema and date filtering are not documented; do not invent them.'],'evidence':[{'id':'catalog','kind':'repo','path':'app/catalog.json','quote':'CSV job export','observed_on':today},{'id':'page','kind':'repo','path':'app/pages.py','quote':'Choose Export on the dispatcher board.','observed_on':today}],'claims':[claim]}
strategy.save(cfg,'understand',u)
snap=sorted((r/'.seo-engine/reports/research').glob('*8d0af0b*.json'))[0]
quote='From the QuoteIQ Team'
assert quote in snap.read_text()
candidates=[]
for ident,page,action,hours in [('export','/guides/export-jobs','Improve the existing CSV export help page',1),('offline','/','Clarify the online scheduling requirement on the homepage',2)]:
 candidates.append({'id':ident,'query':'HVAC job CSV export' if ident=='export' else 'HVAC scheduling offline','audience':'HVAC dispatcher teams','intent':'complete the product task','page':page,'action':action,'original_value':'Explain only the actual documented capability and point back to the product.','business_reason':'Existing customer questions identify friction in a task that the product actually supports.','business_value':2,'effort_hours':hours,'evidence':[{'kind':'customer_question','reference':'support/questions.md','snapshot':'support/questions.md','observation':'Synthetic customer questions ask about CSV export and offline use.','observed_on':today}]})
market={'author':'Independent Codex Reviewer','market_summary':'Real web search reveals vendor-authored broad HVAC comparisons; independent customer demand here is only synthetic fixture data, and no real volume is inferred.','questions':['Where is the daily job export?'], 'competitors':[{'name':'QuoteIQ','observation':'Fetched vendor-authored comparison emphasizes broad dispatch software; rankings and prices are unverified marketing assertions.','evidence_ids':['market-page']}], 'opportunities':candidates,'unknowns':['Actual target-site demand and competitive difficulty remain unmeasured.'],'evidence':[{'id':'market-page','kind':'web','path':str(snap.relative_to(r)),'url':'https://myquoteiq.com/top-10-best-job-management-software-for-hvac-businesses-in-2026/','quote':quote,'observed_on':today},{'id':'support','kind':'customer','path':'support/questions.md','quote':'Where do I find our daily job export?','observed_on':today}],'claims':[{'text':'A vendor-authored HVAC comparison is visible for the tested query.','kind':'fact','evidence_ids':['market-page']}]}
strategy.save(cfg,'research',market)
pos={'author':'Independent Codex Reviewer','audience':'HVAC dispatcher and office teams','problem':'Finding the existing CSV export workflow','promise':'Explain the documented Export entry point and supported capability.','differentiation':'Specific product help instead of an unverified best-software ranking.','message_rules':['No payroll, offline capability, date selector or CSV column promises.'],'copy_briefs':[{'page':'/guides/export-jobs','reader_job':'Find CSV export','angle':'Concise product-specific explanation','cta':'Return to DispatchPad product overview','claims':[claim]}],'unknowns':['Whether this support improvement will acquire visitors is a hypothesis.'],'claims':[claim]}
p=strategy.save(cfg,'position',pos); report['cold_start_next']=strategy.status(cfg)['next_section']
# Changed declared source dependency does not invalidate memory unless separately cited.
build=r/'app/build.py'; old=build.read_text(); build.write_text(old+'\n# Different build dependency revision\n');report['after_source_dependency_change']=strategy.status(cfg)['next_section'];build.write_text(old)
subprocess.run([sys.executable,'app/build.py'],cwd=r,check=True)
brief={'id':'independent-export','simulation':True,'site_url':'https://dispatchpad.test','position_digest':p['digest'],'hypothesis':'A clear product-specific export help page may attract relevant support and organic visits.','reader_need':'HVAC office teams need to find the existing product export entry point.','original_value':'A concise answer based solely on the documented product export capability.','demand_evidence':'Synthetic support questions inform this behavioral fixture; actual demand is unmeasured.','rollback':'Restore the previous app/pages.py source and rebuild the existing route.','source_files':['app/pages.py','app/catalog.json','app/build.py'],'pages':[{'path':'/guides/export-jobs','expected_text':'Export HVAC jobs as CSV','baseline_file':'generated/guides/export-jobs/index.html'}],'selection':{'candidates':candidates,'selected_id':'export','rationale':'The existing export guide directly answers two recorded fixture questions with less scope than a homepage repositioning.'},'commands':u['commands']}
job=growth.create(r,brief)
source=r/'app/pages.py'; pages={};exec(source.read_text(),pages);content=pages['PAGES'];content['/guides/export-jobs']={'title':'Export HVAC jobs as CSV | DispatchPad','body':'<h1>Export HVAC jobs as CSV</h1><p>DispatchPad supports CSV job export for HVAC office teams.</p><h2>Find the export</h2><p>Choose Export on the dispatcher board.</p><p><a href="/">Explore DispatchPad scheduling</a></p>'};source.write_text('PAGES = '+repr(content)+'\n')
growth.validate(r,job)
from bs4 import BeautifulSoup
html=(r/'generated/guides/export-jobs/index.html').read_text();soup=BeautifulSoup(html,'html.parser');assert soup.h1.text=='Export HVAC jobs as CSV';assert soup.a['href']=='/';assert '$999' not in html and 'payroll' not in html
report.update(source_changed=True,route_preserved=True,validation=job['status'],deployed=False,traffic_outcome='unknown',rendered_html_bytes=len(html.encode()),real_external_source_bytes=snap.stat().st_size)
(Path(__file__).parent/'round1-results.json').write_text(json.dumps(report,indent=2));print(json.dumps(report,indent=2))
