"""geo-optimize: llms.txt scaffolding -- agentic-browsing use case ONLY.

references/geo-playbook.md §1 is unambiguous: publishing an llms.txt file
does NOT improve AI-search citation. A June 2026 Ahrefs study of 137,210
domains found 97% of published llms.txt files received zero requests, and an
independent 90-day/60,000-visit experiment found AI platforms never cited a
.md URL. Google's own AI-search guidance says the same. Do not present this
script's output as a visibility/GEO improvement to a user or in any report.

The one narrow, honestly-labeled use case this script serves is different:
agentic browsing / agent-to-agent machine-readability -- giving a coding
agent or automation a concise, structured map of a site's own key pages, so
IT (not a human search user, not an AI-search citation engine) can navigate
the site more efficiently when asked to. Think of it as a sitemap.xml for
agents rather than crawlers, not a citation lever.

This script:
  - Only runs when explicitly invoked (never auto-triggered by seo-maintain).
  - Writes to the STATIC SOURCE directory recorded by seo-setup
    (`static_source_dir` in .seo-engine/config.yml) so the file survives
    builds and is actually served at /llms.txt. Falls back to the repo root
    with an explicit warning when that key is absent, and REFUSES to write
    into the build output directory (`build_output_dir`) -- files there are
    wiped by the next build -- unless --allow-build-output is passed.
  - Refuses to overwrite an existing llms.txt without --force (per
    geo-playbook.md §1: "If a target repo already has one, leave it be
    (harmless) but don't prioritize maintaining it").
  - Builds content strictly from real, crawlable pages (via the shared
    snapshot store, scripts.lib.snapshots) -- never invents URLs or
    descriptions.
  - Labels its own output: llms.txt is markdown, so the disclaimer is a
    `> Note:` blockquote right under the H1 (an HTML comment before the H1
    would break the informal llms.txt convention of H1-first), stating the
    honest scope so a future reader (human or agent) isn't misled into
    thinking it's a citation-boosting artifact.

Usage:
    python3 scaffold_llms_txt.py --max-pages 60 --dry-run
    python3 scaffold_llms_txt.py --max-pages 60 --out /path/to/llms.txt --force
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from urllib.parse import urlparse


if sys.version_info < (3, 9):
    sys.exit("seo-engine requires Python 3.9+ (found %d.%d)" % sys.version_info[:2])


def _find_engine_root(start: Path) -> Path:
    import os

    env = os.environ.get("SEO_ENGINE_ROOT")
    if env and (Path(env) / "scripts" / "lib" / "config.py").is_file():
        return Path(env)
    for candidate in [start, *start.parents]:
        if (candidate / "scripts" / "lib" / "config.py").is_file():
            return candidate
    raise SystemExit(
        "Could not locate seo-engine root (scripts/lib/config.py). If skills were "
        "copied (not symlinked), set SEO_ENGINE_ROOT=/path/to/seo-engine."
    )


sys.path.insert(0, str(_find_engine_root(Path(__file__).resolve())))
from scripts.lib import config as config_module  # noqa: E402
from scripts.lib import pagerules, snapshots  # noqa: E402
from scripts.lib.config import MissingConfigError  # noqa: E402

# llms.txt is markdown: H1 first (the informal convention), THEN the honest-
# scope disclaimer as a `> Note:` blockquote. Same anti-hype text the old
# HTML comment carried, in a form markdown readers actually render.
DISCLAIMER_LINES = [
    "> Note: This file is a machine-readable page map for AGENTIC BROWSING /",
    "> agent-to-agent use (a coding agent or automation reading this site's",
    "> own page map), generated by seo-engine's geo-optimize skill. Per",
    "> references/geo-playbook.md §1 it is NOT expected to and does NOT",
    "> improve AI-search citation (ChatGPT, Perplexity, Google AI Overviews/",
    "> AI Mode, Claude, Gemini, Copilot): a June 2026 Ahrefs study of 137,210",
    "> domains found 97% of published llms.txt files receive zero requests,",
    "> and an independent 60,000-visit study found AI platforms never cited a",
    "> .md URL. Do not present this file to stakeholders as a visibility win.",
]


def collect_pages(snap: "snapshots.Snapshot", max_pages: int) -> list[dict]:
    """Real, indexable, titled pages from the snapshot (no invented URLs or
    descriptions), capped at max_pages in crawl order."""
    pages: list[dict] = []
    for record in snap.pages():
        if not pagerules.is_indexable_html(record):
            continue
        if not (record.get("title") or "").strip():
            continue
        pages.append(record)
        if len(pages) >= max_pages:
            break
    return pages


def build_llms_txt(site_url: str, pages: list[dict]) -> str:
    """Render a minimal llms.txt: an H1 site name, the `> Note:` disclaimer
    blockquote, and a flat list of `- [Title](URL): meta description` entries
    grouped by the first path segment. This mirrors the informal llms.txt
    convention (H1 + link list) without claiming any citation benefit."""
    parsed = urlparse(site_url)
    site_name = parsed.netloc or site_url

    # Group by first path segment so the output has some structure beyond a
    # flat dump -- purely for machine/agent readability, not SEO.
    groups: dict[str, list[dict]] = {}
    for record in pages:
        path = urlparse(record.get("final_url") or record.get("url") or "").path.strip("/")
        segment = path.split("/", 1)[0] if path else "top-level"
        groups.setdefault(segment or "top-level", []).append(record)

    lines = [f"# {site_name}", ""]
    lines.extend(DISCLAIMER_LINES)
    lines.append("")

    for segment in sorted(groups):
        lines.append(f"## {segment}")
        for record in sorted(groups[segment], key=lambda r: r.get("url") or ""):
            url = record.get("final_url") or record.get("url") or ""
            title = (record.get("title") or "").strip()
            desc = (record.get("meta_description") or "").strip()
            entry = f"- [{title}]({url})"
            if desc:
                entry += f": {desc}"
            lines.append(entry)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _resolve_dir(repo_root: Path, value: str) -> Path:
    p = Path(value)
    return (p if p.is_absolute() else repo_root / p).resolve()


def main() -> None:
    import argparse
    import time

    parser = argparse.ArgumentParser(
        description=(
            "Scaffold a minimal llms.txt for agentic-browsing machine-readability. "
            "NOT a citation/visibility mechanism -- see geo-playbook.md §1."
        )
    )
    parser.add_argument("--max-pages", type=int, default=60,
                        help="max pages listed in the page map (also the crawl cap "
                             "when a fresh crawl is needed; default 60)")
    parser.add_argument("--out", default=None,
                        help="output path (default: <static_source_dir>/llms.txt from "
                             ".seo-engine/config.yml, falling back to <repo_root>/llms.txt)")
    parser.add_argument("--force", action="store_true",
                        help="overwrite an existing llms.txt (default: refuse and exit cleanly)")
    parser.add_argument("--allow-build-output", action="store_true",
                        help="permit writing into the configured build_output_dir "
                             "(default: refuse -- the next build wipes files there)")
    parser.add_argument("--ignore-robots", action="store_true",
                        help="only for your own localhost/staging builds")
    parser.add_argument("--dry-run", action="store_true",
                        help="print the would-be content and result without writing the file")
    args = parser.parse_args()

    cfg = config_module.load()
    snapshots.prune(cfg)
    try:
        site_url = cfg.site_url
    except MissingConfigError as exc:
        result = {
            "written": False,
            "error": (
                f"No site URL configured: {exc}. Run the seo-setup skill to write "
                ".seo-engine/config.yml, or export SEO_SITE_URL."
            ),
        }
        json.dump(result, sys.stdout, indent=2)
        print()
        sys.exit(1)

    warning = None
    if args.out:
        out_path = Path(args.out)
    else:
        static_dir = str((cfg.site or {}).get("static_source_dir") or "").strip()
        if static_dir:
            out_path = _resolve_dir(cfg.repo_root, static_dir) / "llms.txt"
        else:
            out_path = cfg.repo_root / "llms.txt"
            warning = (
                "static_source_dir is not recorded in .seo-engine/config.yml -- "
                "falling back to the repo root. Risk: for framework builds the "
                "repo root is NOT the served document root, so /llms.txt may "
                "never be deployed or served in production. Re-run seo-setup "
                "(detect_stack) to record static_source_dir, then regenerate."
            )

    result: dict = {
        "site_url": site_url,
        "out_path": str(out_path),
        "geo_citation_disclaimer": (
            "This file does not improve AI-search citation visibility "
            "(geo-playbook.md §1). It is generated ONLY for agentic-browsing / "
            "agent-to-agent machine-readability."
        ),
        "written": False,
    }
    if warning:
        result["warning"] = warning

    # Never write into the build output directory: the next build wipes or
    # regenerates it, silently deleting the file (same failure mode as the
    # IndexNow key-file placement bug this engine already fixed).
    build_dir = str((cfg.site or {}).get("build_output_dir") or "").strip()
    if build_dir:
        build_path = _resolve_dir(cfg.repo_root, build_dir)
        if out_path.parent.resolve() == build_path:
            if args.dry_run and not args.allow_build_output:
                result["warning_build_output"] = (
                    f"resolved output dir {out_path.parent} equals the configured "
                    "build_output_dir -- a real run would refuse to write here "
                    "(files in the build output are wiped by the next build). "
                    "Target static_source_dir instead, or pass --allow-build-output."
                )
            elif not args.allow_build_output:
                result["refused"] = True
                result["error"] = (
                    f"Refusing to write llms.txt into {out_path.parent}: it equals "
                    "the configured build_output_dir, and files written there are "
                    "deleted/overwritten by the next build. Write it to the static "
                    "source directory (static_source_dir in .seo-engine/config.yml) "
                    "so the build pipeline copies it into the output, or pass "
                    "--allow-build-output to override."
                )
                json.dump(result, sys.stdout, indent=2)
                print()
                sys.exit(1)

    if out_path.is_file() and not args.force and not args.dry_run:
        result["skipped_reason"] = (
            f"{out_path} already exists. geo-playbook.md §1: if a target repo "
            "already has one, leave it be (harmless) but don't prioritize "
            "maintaining it. Pass --force to regenerate it anyway."
        )
        json.dump(result, sys.stdout, indent=2)
        print()
        return

    # Crawl via the shared snapshot store: reuse a recent snapshot when one
    # exists, else crawl fresh. --ignore-robots always crawls fresh (a reused
    # robots-respecting snapshot is not what the caller asked for).
    if args.ignore_robots:
        snap = snapshots.new_crawl(cfg, "geo-optimize", max_pages=args.max_pages,
                                   ignore_robots=True)
        reused = False
    else:
        maybe = snapshots.latest(cfg, max_age_hours=24)
        reused = maybe is not None
        snap = maybe or snapshots.new_crawl(cfg, "geo-optimize", max_pages=args.max_pages)
    result["snapshot"] = {
        "path": snap.path.name,
        "producer_skill": snap.meta.get("producer_skill", ""),
        "reused": reused,
        "pages_crawled": snap.pages_crawled,
    }

    pages = collect_pages(snap, args.max_pages)
    if not pages:
        summary = snap.meta.get("crawl_summary", {})
        result["empty_crawl_reason"] = {
            "robots_status": summary.get("robots_status", ""),
            "all_blocked": summary.get("all_blocked", False),
        }

    content = build_llms_txt(site_url, pages)
    result["page_count"] = len(pages)
    result["preview"] = content[:2000]

    if args.dry_run:
        result["dry_run"] = True
        json.dump(result, sys.stdout, indent=2)
        print()
        return

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    result["written"] = True

    stamp = time.strftime("%Y%m%d-%H%M%S")
    report_path = cfg.reports_dir / f"geo-llms-txt-scaffold-{stamp}.json"
    report_path.write_text(json.dumps(result, indent=2), encoding="utf-8")

    state_path = cfg.state_dir / "geo-llms-txt-last-run.json"
    state_path.write_text(json.dumps({
        "site_url": site_url,
        "out_path": str(out_path),
        "page_count": result["page_count"],
        "report_path": str(report_path),
    }, indent=2), encoding="utf-8")

    json.dump(result, sys.stdout, indent=2)
    print()


if __name__ == "__main__":
    main()
